#define _ENABLE_LOGS_INFO_
#define _ENABLE_LOGS_INFO_TIME_
#define _ENABLE_LOGS_INFO_DIR_
//#define _ENABLE_LOGS_VERBOSE_
//#define _ENABLE_LOGS_VERBOSE_2_
#define _ENABLE_LOGS_ERR_
#define _ENABLE_LOGS_INFO_RESULT_INTERNAL_
#define _ENABLE_LOGS_INFO_RESULT_

